import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
      <div >
        <ul className='header'>
          <li><Link href="/"> Acceuil</Link> </li>
          <li><Link href="/contact">Contact</Link> </li>
          <li><Link href="/about">About</Link> </li>
        </ul>
      </div>
     {children}</body>
    </html>
  )
}
